# Goal is to move around obstacle
bool obstacle_ahead  # We've reached an obstacle
---
# Result that will be published after the action execution ends.
bool way_clear
---
# feedback message that will be published during action execution.
uint32 time_passed

